### ISSUE TITLE
New install.. missing files?

### ISSUE THREAD

**Issue by phoniclynx** [a15lam/php-wemo#4]
The test example require a file called 'autoload.php' in a folder called vendor.... folder does't exist therefore the file doesn't exist.

Not sure how to load the program's if the example code doesn't work?

_```
Warning: require(/var/www/html/wemo/examples/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/wemo/examples/console.php on line 2

Fatal error: require(): Failed opening required '/var/www/html/wemo/examples/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/wemo/examples/console.php on line 2

``` _
```

**Comment by df-arif** [comment]
You need to install composer (dependency manager) if you don't have it already. See http://getcomposer.org . Once it's installed run "composer update" to install all dependencies. Then try running the examples using cli.

**Comment by phoniclynx** [comment]
ok.. So I ran update... and installed with composer originally. not too sure how this works.

I ran the install for composer in my home folder.. was I supposed to do something else? have I done it wrong.. instructions on it were rather vague.

**Comment by phoniclynx** [comment]
OK got it to run by installing it into my /www/var/html/wemo dir.. now I'm having another issue where I can't get a class to run?

Fatal error: Call to undefined method a15lam\PhpWemo\Discovery::getBaseDeviceByName() in /var/www/html/wemo/examples/test.php on line 32

This is the ONE thing that I wanted it for.. that and being able to tell if a switch is actually on or off.

**Comment by a15lam** [comment]
I used the test.php file to try out different things as I was working on this. So, not all the commented out lines are accurate. So, instead try the following. This will turn on/off your bulb/switch. You can also try running the console.php in examples to see all your wemo devices and control them.

```
<?php
require __DIR__ . '/../vendor/autoload.php';

$wb = \a15lam\PhpWemo\Discovery::getDeviceByName('name of your wemo device'); // Name of your device as it shows on your wemo app.
$wb->on();
sleep(2);
echo "state:".$wb->state().PHP_EOL;
sleep(2);
$wb->off();
sleep(1);
echo "state:".$wb->state().PHP_EOL;
```

**Comment by phoniclynx** [comment]
![image](https://cloud.githubusercontent.com/assets/3883152/15361510/ec853616-1d50-11e6-9765-40389982d003.png)

Console didn't work... drove it crazy.. but I managed to get it to work this way:

$switch = \a15lam\PhpWemo\Discovery::getDeviceByName($row->deviceName);

**Comment by df-arif** [comment]
console.php is not meant to run on the browser. You will need to run this on command line -

```
php /path/to/your/install/examples/console.php
```

I know this lacks details documentation which I am looking forward to work on as time allows. Anyway, I am glad you got the code working at least.
