### ISSUE TITLE
array return

### ISSUE THREAD

**Issue by phoniclynx** [a15lam/php-wemo#6]
Hello,

Is it at all possible to change this output we get from the array.. would make the programming sooooo much easier:
Array
(
    [0] => Array
        (
            [id] => fan
            [ip] => 192.168.0.201
            [deviceType] => urn:Belkin:device:controllee:1
            [friendlyName] => Fan
            [modelName] => Socket
            [UDN] => uuid:Socket-1_0-221526K110047E
            [class_name] => a15lam\PhpWemo\Devices\WemoSwitch
        )

```
[1] => Array
    (
        [id] => heater
        [ip] => 192.168.0.179
        [deviceType] => urn:Belkin:device:controllee:1
        [friendlyName] => Heater
        [modelName] => Socket
        [UDN] => uuid:Socket-1_0-221524K1100DBB
        [class_name] => a15lam\PhpWemo\Devices\WemoSwitch
    )
```

)

to:
Array
(
    [fan] => Array
        (
            [ip] => 192.168.0.201
            [deviceType] => urn:Belkin:device:controllee:1
            [friendlyName] => Fan
            [modelName] => Socket
            [UDN] => uuid:Socket-1_0-221526K110047E
            [class_name] => a15lam\PhpWemo\Devices\WemoSwitch
        )

```
[heater] => Array
    (
        [ip] => 192.168.0.179
        [deviceType] => urn:Belkin:device:controllee:1
        [friendlyName] => Heater
        [modelName] => Socket
        [UDN] => uuid:Socket-1_0-221524K1100DBB
        [class_name] => a15lam\PhpWemo\Devices\WemoSwitch
    )
```

)

**Comment by df-arif** [comment]
It is possible but what makes it so difficult to use it the way it is? You can always write a helper function to access this array by device id or name or any key. Or write a function to convert this array exactly the way you need it before you use it in your program.

**Comment by phoniclynx** [comment]
why? because it would make more sense.. grab it as an key.. and not as a
random number... getting it the way it is now you have to make it work and
then sort... having it with an array with the keys.. you can always get the
array_keys or if you happen to know it already (ie is in a database) you
just have to refer to it by it's key name.

**Comment by df-arif** [comment]
Will consider this for next release/update. For now, I would suggest creating a helper function to access this array however way you want.
